### ISSUE TITLE
Compatability issues with ubuntu

### ISSUE THREAD

**Issue by sainikhileshreddy** [Rishav-hub/GNetTrainer-package#1]
- [ ]  Add PyYaml to requirements
- [ ] Remove Windows specific directory paths

**Comment by Rishav-hub** [comment]
Thank You for pointing this out. I will be fixing it within 2-3 days.

**Comment by Rishav-hub** [comment]
The new version of GNetTrainer is launched please try that. I have fixed that issue in it.
